Badge
semliko/test-guru pull request #17
Opened 2021-10-05 15:30 UTC by semliko

2021-10-05 17:12 UTC, BubuntuClu requested changes

2021-10-05 17:12 UTC, BubuntuClu commented on app/controllers/user_badges_controller.rb
> +  before_action :set_user_badge, only: %i[ show edit update destroy ]
у тебя в контроллере нет столько экшенов, а ради одного не надо делать колбэк

2021-10-05 17:12 UTC, BubuntuClu commented on app/controllers/user_badges_controller.rb
> +  def user_badge_params
а это где используется?

2021-10-05 17:12 UTC, BubuntuClu commented on app/controllers/user_badges_controller.rb
> +    params.require(:user_badge).permit(:user_id, :badge_id)
зачем это вообще нужно? ты промежуточную таблицу хочешь заполнять этими данными?

2021-10-05 17:12 UTC, BubuntuClu commented on app/helpers/nav_helper.rb
> +      path = current_user.admin? ? admin_tests_path : root_path
```
def user_home_path
  user_signed_in? && current_user.admin? ? admin_tests_path : root_path
end
```

2021-10-05 17:12 UTC, BubuntuClu commented on app/models/badge.rb
> +  validates_presence_of :image_url, :name
`validates :image_url, :name, presence: true`, самая стандартная ведь валидация, зачем старый синтаксис тут использовать?

2021-10-05 17:12 UTC, BubuntuClu commented on app/models/test_passage.rb
> +    status = success? ? true : false
`update_attribute(:passed, succes?)`
зачем условие вокруг условия ставить? тебе метод и так возаращает true/false

2021-10-05 17:12 UTC, BubuntuClu commented on app/models/test_passage.rb
> +  def add_badge_to_user
выдачей баджей и проверкой должен заниматься отдельный сервис. это не задача модели.
нужно вынести этот код

2021-10-05 17:12 UTC, BubuntuClu commented on app/models/test_passage.rb
> +    if test_attempts.count <= test_attempts.where(passed: true).count && success?
чем больше различных баджей будет, тем больше будет тут кода. надо придумать как избавиться от постоянного дописывания условия

2021-10-05 17:12 UTC, BubuntuClu commented on app/models/test_passage.rb
> +      badges << Badge.where(name: "Test passed from the first attempt").first
есть метод `find_by`, он возвразает один элемент.
но в хорошем варианте тебе вообще не понадобиться каждый раз искать бадж. 
итерируй через все свои баджи

2021-10-05 17:12 UTC, BubuntuClu commented on app/models/test_passage.rb
> +  def same_categiries_tests_passed
опечатка в категории

2021-10-05 17:15 UTC, BubuntuClu requested changes

2021-10-05 17:15 UTC, BubuntuClu commented on app/models/test_passage.rb
> +    TestPassage.joins(:test).where('test_id = ?', test.id).where(user_id: user.id)
`where('test_id = ?', test.id).where(user_id: user.id)` придерживайся одного стиля написания. у тебя два условия и оба написаны по разному. можно одно условие через азпятую написать

2021-10-05 17:15 UTC, BubuntuClu commented on app/models/test_passage.rb
> +    user.test_passages.joins(:test).where(passed: true).where('tests.category_id = ?', test.category.id)
уникальный значения надо считать

2021-10-05 17:15 UTC, BubuntuClu commented on app/models/test_passage.rb
> +    if test_attempts.count <= test_attempts.where(passed: true).count && success?
test_attempts.count <= test_attempts.where(passed: true)
в БД ходишь два раза практически с одним запросом

сравни количество попыток с `1`. тебе ведь надо узнать прошел ли он с первого раза

2021-10-06 17:23 UTC, BubuntuClu requested changes

2021-10-06 17:23 UTC, BubuntuClu commented on app/services/user_badge_service.rb
> +  def call
```
def call
  Badge.all.each do |badge|
    user.badges << badge if send("#{badge.rule}_award?", badge.value)
  end
end
```
таким образом ты сделаешь перебор всех своих бейджей и метод для бейджа скажет надо его добавлять или нет

rule - это правило типа `all_category/all_level/first_attempt`
value - это аргумент для этого правила. какую категорию будем проверять и тд

2021-10-06 17:23 UTC, BubuntuClu commented on app/services/user_badge_service.rb
> +    @test_passage.test_attempts.count <= 1 && @test_passage.success?
чтобы еще раз не запускать логику расчета успеха, используй новое поле passed

2021-10-07 16:58 UTC, semliko commented on app/services/user_badge_service.rb
> +  def call
уж очень кратко вы здесь обьяснили, вот этот момент badge.value, как его сделать динамическим, здесь нужно тогда передавать множественные аргументы а тот метод который мы вызываем должен из них уже выбирать то что ему нужно, какой аргумент здесь должен быть badge.value ?

2021-10-08 06:45 UTC, BubuntuClu commented on app/services/user_badge_service.rb
> +  def badge_value
ну, это не то что я тебе предлагал. зачем для каждого бейджа считать то, что не надо?
в сам бейдж просто занеси значения для правила через новое поле

2021-10-08 08:30 UTC, merged